# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05effaec3a2e40b753e9e50f34e20ed02d138b1ac0af7fb431e005d3330292aff17d0a48fdc8a123dc0390426320634b1cb98e96ef8e7915bba788d1f649a6fa

test:
  secret_key_base: b9dc9a4c6e59322fb2cfde9c5ad7db2a09654307065d2250b3ed197c0f1c3e3f3cd6f411e38b2c62eb6bd3c41699813becab258d9a54cb7e2670e2b4274e951f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
